import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
builtin_box_drawing = false
size                = 11

[font.bold]
family = "IntoneMono Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "IntoneMono Nerd Font"
style  = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "IntoneMono Nerd Font"
style  = "Italic"

[font.normal]
family = "IntoneMono Nerd Font"
style  = "Regular"

[font.offset]
x = 0
y = 0
